name: Zip and Attach Release

on:
  release:
    types: [published]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract Release Tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Zip repository contents
        run: |
          zip -r RCBotSven5-Waypointing-Helper-${{ env.RELEASE_TAG }}.zip . -x ".git/*" ".github/*"

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: RCBotSven5-Waypointing-Helper-${{ env.RELEASE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
